title: Sima Didari
description: Senior Staff AI Scientist - Portfolio
baseurl: ""
url: "https://simadidari.github.io"

markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/