# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sima Didari
title: Senior Staff AI Scientist
email: Sima.Didari@gmail.com
website: https://github.com/SimaDidari/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SimaDidari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: SimaDidari
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: GoogleScholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=e7JYe3cAAAAJ&hl=en



# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sima and I'm a Senior Staff AI Scientist at Samsung SDS AI Science Lab in San Jose CA. 
  Prior to Samsung, I worked as a Data Scientist, and Probabilistic Engineer for Applied Materials and GE Global Research.
  My background is in Bayesian Machine Learning, Deep Learning, and Generative AI. 
  I received my PhD from Georgia Institute of Technology on Topology Optimization
   for Computer-Aided Engineering (CAE) of microstructures under the supervision 
   of Professor Tequila Harris. 

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung SDS, 
        link: www.samsungsds.com
        sub_title: Senior Staff AI scientist
        caption: Feb 2019 - Present
      
        quote: >
          AI Science Lab, San Jose, CA, USA 
          
        description: | # this will include new lines to allow paragraphs
          - Responsibilities : Establishing technical goals, Leading task force & collaborations across Samsung’s or external entities for Technology Development
              & Technology Transfer, Developing products, solutions & services to secure Samsung's competitive advantages. 
          
          - Projects:
            - Generative AI:
              - Development of tailored multi-modal LLMs for data in text, image, and tabular formats
              - Uncertainty quantification and model calibration for text-image multi-modal and large language models
            
            - Data efficient Deep Learning and AI:
              - Development of Representation & Unsupervised Learning algorithms for reducing the labeling need for 
                Deep Learning models 
              - Development of data efficient alignment methods for LLMs

            - Computer Vision:
              - Active Learning and Unsupervised accuracy estimation for classification, detection & semantic segmentation
              - Probabilistic Multi-View 3D semantic segmentation Deep Learning Active Learning framework

            - Predictive data analytics:
              - Developed sale forecasting models for Samsung business units 
              - Optimized marketing strategies for sale campaigns 


      - layout: left
        title: Applied Materials
        link: www.appliedmaterials.com
        sub_title: Senior Data Scientist
        caption: Nov 2017 - Feb 2019
      
        quote: >
          Data Science Group, Santa Clara, CA, USA
          
        description: | # this will include new lines to allow paragraph
          - Development & deployment of AI solutions to increase the performance/ 
              productivity of engineering, services & supply chain teams
          - Leading AI app productization in collaboration with Software, UI, DevOp teams & internal or external customers



      - layout: left
        title: GE Global Research
        link: www.geaerospace.com
        sub_title: Research Engineer
        caption: Aug 2014 - Nov 2017
      
        quote: >
          Probabilistic Lab, San Ramon, CA, USA
           
        description: | # this will include new lines to allow paragraph
          - Development of Probabilistic Methods & Machine Learning models for calibration & validation, uncertainty quantification, 
              optimization and meta-modeling/surrogates modeling
          - Development of Deep Learning & Machine Learning models to optimize engineering design & manufacturing process
          - Development of Computer Vision defect detection software



      


            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2009 - 2014
        sub_title: Ph.D. & M.S., Mechanical Engineering 
        quote: > 
          Research topics: CAE, Topological Characterization & Optmization, Image Proessing
          
        description: | # this will include new lines to allow paragraphs
          - Developed periodic surface parametric models to represent the topology of microstructures
          - Developed voxel-based representations for 3D composite microstructures
          - Conducted topological characterization of 3D models using graph representations
          - Conducted topology optimization for voxel representation of 3D volumes using GA

      - layout: left
        title: University of Tehran 
        caption: 2001 - 2005
        sub_title: B.S., Mechanical Engineering 
        # quote: > 
        #   Research topics: Computer-Aided Engineering (CAE), Topological Characterization, Image Proessing, Genetic Algorithm (GA) Optimization
          


  

  
  - title: Selected Publications
   
    layout: text
    content: | # this will include new lines to allow paragraphs
      - My full publication list can be found at [Scholar profile](https://scholar.google.com/citations?user=e7JYe3cAAAAJ&hl=en).
      Here is the list of my recent publictions:
        - Improving instruction following in language models through proxy-based uncertainty estimation, [arXiv](https://arxiv.org/abs/2405.06424) Accepted at ICML, (2024)
        - Bayesian active learning for semantic segmentation, [arXiv](https://www.arxiv.org/abs/2408.01694), (2024)
        - Self-Supervised contrastive representation learning for 3D mesh segmentation, [arXiv](https://arxiv.org/abs/2208.04278v2),
          Accepted at AAAI, (2023)
        - Highly efficient representation and active learning framework for imbalanced data and
          its application to COVID-19 X-Ray classification, [arXiv](https://arxiv.org/abs/2103.05109v4) NeurIPS Data-Centric AI workshop, (2021)
        - Active learning performance in labeling radiology images is 90% Effective, [Frontiers in Radiology](https://www.frontiersin.org/journals/radiology/articles/10.3389/fradi.2021.748968/full),
          (2021)
        - PatchNet: Unsupervised object discovery based on patch embedding, [arXiv](https://arxiv.org/abs/2106.08599), (2021)
        - Modeling and optimizing the impact of process and equipment parameters in sputtering
          deposition systems using a Gaussian process machine learning framework, 
          [IEEE Transactions on Semiconductor Manufacturing](https://ieeexplore.ieee.org/document/9634119), (2021)

  
  - title: Selected Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Bayesian semantic segmentation active learning with Beta approximation, 20230368507
      - Object discovery, 20220383105
      - Unsupervised representation learning and active learning to improve data efficiency, 20220138935
      - Long short-term memory anomaly detection for multi-sensor equipment monitoring, 20200104639
      - Correcting component failures in ion implant semiconductor manufacturing tool, 11348813
      - Chamber matching with neural networks in semiconductor equipment tools, 11133204
      - Magnetic mixer, 11097236
      - Magnetic drive for bioreactor, 10335750
      - System and method for characterizing conditions in a fluid mixing devices, 10682618


  - title: Awards & Recognitions
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Samsung SDS Circle of Excellence Award granted by CEO of Samsung SDSA
        for Outstanding performance, Creativity, Organizational abilities and Team Work, (2022)
      - Best Presentation Award at Future of Information and Communication Conference (FICC), 
        for the paper titled "Medical Image Labeling via Active Learning is 90% Effective", (2022)
      - GE Above & Beyond Award for development of automated probabilistic testing framework, (2017)
      - GE Global Research Aero-Thermal Mechanical System (ATMS) impact award for outstanding
         contribution to Artificial Lift Optimization project, (2016)
      - ASME's International Engineering Congress and Exposition outstanding research award, (2012)

          

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Proxy-Based Uncertainty Estimation for Improving Instruction Following in Language Models
        link : https://arxiv.org/abs/2405.06424
        link_text: arXiv link
        additional_links:
          - title:  GitHub page for the project
            icon: fab fa-github
            url: https://github.com/SimaDidari/proxy_based_uncertainty
        quote: >
          Accepted at ICML 2024
        description: | # this will include new lines to allow paragraphs
          We defined a novel Uncertainty-aware Reward Model (URM) for the preference training of LLMs 
          based on Bayesian approximation to quantify the uncertainty of paired responses.
          We experimentally demonstrated that using URM in LLMs training boosts their instruction
          following capability and their policy optimization objectives. 
          The URM based finetuning surpasses existing methods by a large margin on benchmarks such as
            Vicuna and MT-bench.

          
          - The code & data for the paper are shared at [P-B-U Git Repo](https://github.com/SimaDidari/proxy_based_uncertainty)
          
          
          ![alt text](/images/dpo.jpg "proxy concept")
  


# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
