# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sima Didari
title: Senior Staff AI Scientist
email: Sima.Didari@gmail.com
website: https://github.com/SimaDidari/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SimaDidari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: SimaDidari
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: GoogleScholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=e7JYe3cAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sima and I'm a Senior Staff AI Scientist at Samsung SDS AI Science Lab in San Jose CA. 
  Prior to Samsung, I worked as a Data Scientist, and Probabilistic Engineer for Applied Materials and GE Global Research.
  My background is in Bayesian Machine Learning, Deep Learning, and Generative AI. 
  I received my PhD from Georgia Institute of Technology on Topology Optimization for Computer-Aided-Design (CAE) of microstructures under the supervision of Professor Tequila Harris. 

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung SDS
        link: www.samsungsds.com
        sub_title: Senior Staff AI scientist
        caption: Feb 2019 - Present
      
        quote: >
          Job description : Establishing technical goals,  Leading the task force and collaborating across Samsung’s entities or external entities for Technology development & technology transfer. 
          Developing and deploying products, solutions & service-differentiated technologies to secure a competitive advantage in business. 
          
        description: | # this will include new lines to allow paragraphs
          - Generative AI and Large Language Model development:
            - Text-to-SQL model development
            - Development of data efficient alignment of LLMs
            - Development of tailored multi modal LLMs for data in text, image, and tabular formats
            - Uncertainty quantification and model calibration for text-image multi-modal and large language models
          
          - Data efficient Deep Learning and AI:
            - Development of Representation and Unsupervised Learning algorithms for reducing the labeling need for Deep Learning models 

          - Computer Vision:
            - Developed active learning and Unsupervised accuracy estimation framework for classification, semantic segmentation
            - Developed probabilistic Multi-View 3D semantic segmentation uncertainty and active learning framework

          - Predictive data analytics:
            - Developed sale forecasting models for Samsung business units 
            - Optimized marketing strategies for sale campaigns 
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2009 - 2014
        sub_title: Ph.D. & M.S., Mechanical Engineering 
        quote: > 
          Research topics: Computer-Aided Engineering (CAE), Topological Characterization \& Optmization, Image Proessing
          
        description: | # this will include new lines to allow paragraphs
          - Developed periodic surface parametric models to represent the topology of microstructures
          - Developed voxel-based representations for 3D composite microstructures
          - Conducted topological characterization of 3D models using graph representations
          - Conducted topology optimization for voxel representation of 3D volumes using GA

      - layout: left
        title: University of Tehran 
        caption: 2001 - 2005
        sub_title: B.S., Mechanical Engineering 
        # quote: > 
        #   Research topics: Computer-Aided Engineering (CAE), Topological Characterization, Image Proessing, Genetic Algorithm (GA) Optimization
          


  

  
  - title: Selected Publications
    layout: text
    
    content: | # this will include new lines to allow paragraphs
      - Bayesian Active Learning for Semantic Segmentation, arXiv:2408.01694, 2024, 
        - url: Link to project (https://arxiv.org/pdf/2408.01694)
      - Improving Instruction Following in Language Models through Proxy-Based Uncertainty Estimation, ICML 2024
      - Unsupervised representation learning and active learning to improve data efficiency, 20220138935
      - Long short-term memory anomaly detection for multi-sensor equipment monitoring, 20200104639
      - Correcting component failures in ion implant semiconductor manufacturing tool, 11348813
      - Chamber matching with neural networks in semiconductor equipment tools, 11133204
      - Magnetic mixer, 11097236
      - Magnetic drive for bioreactor, 10335750
      - System and method for characterizing conditions in a fluid mixing devices, 10682618


  
  - title: Selected Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Bayesian semantic segmentation active learning with Beta approximation, 20230368507
      - Object discovery, 20220383105
      - Unsupervised representation learning and active learning to improve data efficiency, 20220138935
      - Long short-term memory anomaly detection for multi-sensor equipment monitoring, 20200104639
      - Correcting component failures in ion implant semiconductor manufacturing tool, 11348813
      - Chamber matching with neural networks in semiconductor equipment tools, 11133204
      - Magnetic mixer, 11097236
      - Magnetic drive for bioreactor, 10335750
      - System and method for characterizing conditions in a fluid mixing devices, 10682618


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Proxy-Based Uncertainty Estimation for Improving Instruction Following in Language Models
        link: https://github.com/P-B-U/proxy_based_uncertainty.git
        # link_text: Project Website
        additional_links:
          - title:  Proxy-based uncertainty
            icon: fab fa-github
            url: https://github.com/P-B-U/proxy_based_uncertainty.git
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio.
          If you don't have a project as awesome as this I would advise you make one.
  


# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
